# Generated by Django 3.2.2 on 2021-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonsServer', '0002_auto_20200703_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='linkedApplication',
            field=models.ManyToManyField(related_name='linked_application', to='commonsServer.Application'),
        ),
    ]
