# Generated by Django 5.1.15 on 2026-04-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonsServer', '0003_application_linkedapplication'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('name', 'application'), name='unique_test_for_application'),
        ),
        migrations.AddConstraint(
            model_name='testenvironment',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_environment'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('name', 'application'), name='unique_name_for_application'),
        ),
    ]
