# Generated by Django 5.1.15 on 2026-06-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonsServer', '0004_application_unique_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('initialValue', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application preference',
                'verbose_name_plural': 'Application preferences',
                'ordering': ('key',),
            },
        ),
    ]
