"""
Django settings for seleniumRobotServer project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
# Login/ mdp: admin / adminServer
import os
from seleniumRobotServer.settings_base import *

from django_auth_ldap.config import LDAPSearch, LDAPGroupQuery,\
    ActiveDirectoryGroupType
import ldap

CLEANING_CRON = "* * * * *"                 # clean every minute

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=y2v$6)efr14kk4#n@jl3avrtklc*#l_c%0bffu21k%d6w&89m'
VARIABLE_SECRET_KEY = b'aqwxszedcvfrtgbnhyujABkiolCmp123' # 32 bytes long

TIME_ZONE = 'Europe/Paris'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# allow files up to 10 MB to be uploaded
FILE_UPLOAD_MAX_MEMORY_SIZE = 10000000
# allow files as variable value up to 10 MB to be uploaded
VAR_UPLOAD_FILE_MAX_SIZE = 10000000
AUTHENTICATION_BACKENDS = (
    "seleniumRobotServer.ldapbackends.LDAPBackend1", "seleniumRobotServer.ldapbackends.LDAPBackend2", "seleniumRobotServer.ldapbackends.LDAPBackend3",
    'django.contrib.auth.backends.ModelBackend',
    # 'seleniumRobotServer.openidbackend.NameOIDCAB',
    #  'mozilla_django_oidc.auth.OIDCAuthenticationBackend'
)

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    # LOCAL
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'seleniumuser',
        'PASSWORD': 'selenium',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# whether to enable security of API / GUI
SECURITY_WEB_ENABLED = "True"
SECURITY_API_ENABLED = "True"

if (SECURITY_API_ENABLED):
    REST_FRAMEWORK = {
        # Use Django's standard `django.contrib.auth` permissions,
        'DEFAULT_PERMISSION_CLASSES': [
            'seleniumRobotServer.permissions.permissions.GenericPermissions'
        ],
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'hashed_auth.authentication.TokenAuthentication',   # for API calls
            'rest_framework.authentication.SessionAuthentication', # for Ajax requests from GUI
        ]
    }
else:
    REST_FRAMEWORK = {
        # allow read-only access for unauthenticated users.
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.AllowAny'
        ]
    }

# Connection to Open-WebUI instance. set empty URL to disable
OPEN_WEBUI_WORKERS = 2
OPEN_WEBUI_URL = 'http://zld7205v.societe.mma.fr:8080'
OPEN_WEBUI_TOKEN = 'sk-a3b8b2486b494a59ad3ec73b0e8a1214'
OPEN_WEBUI_MODEL = 'ministral-3:8b'
OPEN_WEBUI_PROMPT_FIND_ERROR_MESSAGE = '''In the provided image, do you see an error message ?
- Start by extracting all texts and their color
- Then, for each text, depending on its colour and meaning, determine if the text is an error message

Reply only in JSON, with the following format:
```
{"explanation": "<what leads to your conclusion>", "error_messages": [<list of detected error messages or technical failures as STRING]}
```
‘error_messages’ key may have an empty value if no error message or technical failure has been detected
Check that the JSON response is valid'''
OPEN_WEBUI_PROMPT_WEBPAGE_COMPARISON = '''You are a tester that wants to check a test result.
These 2 pictures represent web pages.
Your goal is to say if the 2 pictures are from the same web page (even if some textual information differ).
You will base your response on:
- page layout / content layout
- general design
- position of graphical elements like buttons, text fields, tabs
- color scheme of graphical elements

Your response should NOT be based on:
- text data that may vary from user or customer

You will consider that the 2 pictures represent the same web page with a percentage of confidence (100% same page, 0% not the same page) if layout, general design, position and color of graphical elements look similar.

Reply only in JSON, with the following format:
```
{"explanation": "<what leads to your conclusion>", "similarity": <percentage of confidence as INTEGER>}
```
Check that the JSON response is valid
'''
OPEN_WEBUI_PROMPT_FIND_ELEMENT = '''In the provided picture, tell me if the %s is present or not.
For this:
- analyze the picture, looking for text fields, buttons, tabs and texts
- say if the requested field is present

Reply only in JSON, with the following format:
```
{"explanation": "<what leads to your conclusion>", "present": <true/false>}
```
Check that the JSON response is valid
'''

# -------- Application specific flags ------------
# whether we restrict the view/change/delete/add to the user, in admin view to only applications he has rights for (issue #28)
RESTRICT_ACCESS_TO_APPLICATION_IN_ADMIN = True

# -------- OpenID Authentication -----------------
OIDC_RP_CLIENT_ID = 'seleniumserver-TI'
OIDC_RP_CLIENT_SECRET = 'bQ96iNN88rVq5Us0m2YY'
OIDC_OP_AUTHORIZATION_ENDPOINT = "https://coveauth-ass.itmma.fr/coveauth-server/oauth2/authorization"
OIDC_OP_TOKEN_ENDPOINT = "https://coveauth-ass.itmma.fr/coveauth-server/oauth2/token"
OIDC_OP_USER_ENDPOINT = "https://coveauth-ass.itmma.fr/coveauth-server/oauth2/userInfo"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "sub"
OIDC_USE_NONCE = False
OIDC_RP_IDP_KEYFILE = ''
if os.path.isfile(OIDC_RP_IDP_KEYFILE):
    with(open(OIDC_RP_IDP_KEYFILE)) as keyfile:
        OIDC_RP_IDP_SIGN_KEY = keyfile.read()
OIDC_OP_JWKS_ENDPOINT = 'https://coveauth-ass.itmma.fr/coveauth-server/keys/json-web-key-set'

# to use in conjunction with 'NameOIDCAB' backend
OIDC_IS_STAFF_GROUP_NAMES = ['Users']
OIDC_IS_SUPERUSER_GROUP_NAMES = []
 
# -------- LDAP Authentication -------------------
AUTH_LDAP_GLOBAL_OPTIONS = {
    ldap.OPT_REFERRALS: 0
}
 
# first LDAP server configuration
AUTH_LDAP_1_SERVER_URI = "ldap://societe.mma.fr:389"
AUTH_LDAP_1_BIND_DN = 'CN=zpsmojenkins,OU=ComptesDeService,DC=societe,DC=mma,DC=fr'
AUTH_LDAP_1_BIND_PASSWORD = 'WzUCO6nfahcpV0b1GVP2'
AUTH_LDAP_1_USER_SEARCH = LDAPSearch("DC=societe,DC=mma,DC=fr", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
AUTH_LDAP_1_GROUP_SEARCH = LDAPSearch("DC=societe,DC=mma,DC=fr", ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_1_GROUP_TYPE = ActiveDirectoryGroupType()
AUTH_LDAP_1_USER_ATTR_MAP = {"first_name": "givenName", "last_name": "sn"}
AUTH_LDAP_1_USER_FLAGS_BY_GROUP = {
#     "is_active": (LDAPGroupQuery("CN=RACP_Selenium_001,OU=Selenium,OU=RessAppli,OU=Groupes,DC=societe,DC=mma,DC=fr") |
#                   LDAPGroupQuery("CN=RACP_Selenium_003,OU=Selenium,OU=RessAppli,OU=Groupes,DC=societe,DC=mma,DC=fr")),
    "is_staff": "CN=RACP_Selenium_003,OU=Selenium,OU=RessAppli,OU=Groupes,DC=societe,DC=mma,DC=fr",
    "is_superuser": "CN=RACP_Selenium_001,OU=Selenium,OU=RessAppli,OU=Groupes,DC=societe,DC=mma,DC=fr"
}


# second LDAP server configuration (uncomment "seleniumRobotServer.ldapbackends.LDAPBackend2" in AUTHENTICATION_BACKENDS to use it)
AUTH_LDAP_2_SERVER_URI = "ldap://maafprod.e-corail.com:389"
AUTH_LDAP_2_BIND_DN = 'CN=zpsmojenkins,OU=Jenkins,OU=Administration,DC=maafprod,DC=e-corail,DC=com'
AUTH_LDAP_2_BIND_PASSWORD = 'oT7B7y1wMSQj0F'
AUTH_LDAP_2_USER_SEARCH = LDAPSearch("DC=maafprod,DC=e-corail,DC=com", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
AUTH_LDAP_2_GROUP_SEARCH = LDAPSearch("DC=maafprod,DC=e-corail,DC=com", ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_2_GROUP_TYPE = ActiveDirectoryGroupType()
AUTH_LDAP_2_USER_ATTR_MAP = {"first_name": "givenName", "last_name": "sn"}
AUTH_LDAP_2_USER_FLAGS_BY_GROUP = {
#     "is_active": (LDAPGroupQuery("CN=RACP_SELENIUM_001,OU=groupes_fonctionnels,OU=groupes,DC=maafprod,DC=e-corail,DC=com") |
#                   LDAPGroupQuery("CN=RACP_SELENIUM_003,OU=groupes_fonctionnels,OU=groupes,DC=maafprod,DC=e-corail,DC=com")),
    "is_staff": "CN=RACP_SELENIUM_003,OU=groupes_fonctionnels,OU=groupes,DC=maafprod,DC=e-corail,DC=com",
    "is_superuser": "CN=RACP_SELENIUM_001,OU=groupes_fonctionnels,OU=groupes,DC=maafprod,DC=e-corail,DC=com"
}

# third LDAP server configuration (uncomment "seleniumRobotServer.ldapbackends.LDAPBackend3" in AUTHENTICATION_BACKENDS to use it)
AUTH_LDAP_3_SERVER_URI = "ldaps://ads01.priv:636"
AUTH_LDAP_3_BIND_DN = 'CN=Compte applicatif JENKINS-TESTS,OU=CPTES_SRV,OU=OBJETS_ADMIN,OU=InfraTech,DC=ads01,DC=priv'
AUTH_LDAP_3_BIND_PASSWORD = '0zyN4miW5szkLsr7ejYI'
AUTH_LDAP_3_USER_SEARCH = LDAPSearch("DC=ads01,DC=priv", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
AUTH_LDAP_3_GROUP_SEARCH = LDAPSearch("DC=ads01,DC=priv", ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_3_GROUP_TYPE = ActiveDirectoryGroupType()
AUTH_LDAP_3_USER_ATTR_MAP = {"first_name": "givenName", "last_name": "sn"}
AUTH_LDAP_3_USER_FLAGS_BY_GROUP = {
#     "is_active": (LDAPGroupQuery("CN=RACP_SELENIUM_001,OU=SELENIUM,OU=APPLICATION,OU=ORGANISATION,DC=ads01,DC=priv") |
#                   LDAPGroupQuery("CN=RACP_SELENIUM_003,OU=SELENIUM,OU=APPLICATION,OU=ORGANISATION,DC=ads01,DC=priv")),
    "is_staff": "CN=RACP_SELENIUM_003,OU=SELENIUM,OU=APPLICATION,OU=ORGANISATION,DC=ads01,DC=priv",
    "is_superuser": "CN=RACP_SELENIUM_001,OU=SELENIUM,OU=APPLICATION,OU=ORGANISATION,DC=ads01,DC=priv"
}
