# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonsServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=300)),
                ('releaseDate', models.DateTimeField(null=True)),
                ('internal', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=500, null=True)),
            ],
            options={
                'permissions': (('see_protected_var', 'Can see protected vars'),),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('commonsServer.application',),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('commonsServer.testcase',),
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('commonsServer.testenvironment',),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('commonsServer.version',),
        ),
        migrations.AddField(
            model_name='variable',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variableServer.Application'),
        ),
        migrations.AddField(
            model_name='variable',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variableServer.TestEnvironment'),
        ),
        migrations.AddField(
            model_name='variable',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variableServer.TestCase'),
        ),
        migrations.AddField(
            model_name='variable',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variableServer.Version'),
        ),
    ]
