# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('variableServer', '0002_variable_reservable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
        migrations.AddField(
            model_name='variable',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='variable',
            name='timeToLive',
            field=models.IntegerField(default=-1, help_text="number of days this variable will live before being destroyed. If < 0, this variable will live forever"),
        ),
        migrations.AlterField(
            model_name='variable',
            name='reservable',
            field=models.BooleanField(default=False, help_text='tick it if this variable should be reserved when used to prevent other tests to use it at the same time. Default is false'),
        ),
    ]
