# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variableServer', '0003_auto_20180710_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
