# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variableServer', '0004_auto_20190318_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='test',
        ),
        migrations.AddField(
            model_name='variable',
            name='test',
            field=models.ManyToManyField(to='variableServer.TestCase'),
        ),
    ]
