# Generated by Django 3.2.25 on 2024-12-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variableServer', '0005_auto_20190402_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterField(
            model_name='variable',
            name='internal',
            field=models.BooleanField(default=False, help_text="tick it if this variable has been created by a selenium test. Variable of such type should be prefixed with 'custom.test.variable'"),
        ),
    ]
