# Generated by Django 3.2.25 on 2025-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variableServer', '0006_auto_20241231_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
