# Generated by Django 3.2.25 on 2025-12-17 13:58

from django.db import migrations, models
import variableServer.models


class Migration(migrations.Migration):

    dependencies = [
        ('variableServer', '0007_alter_variable_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='uploadFile',
            field=models.FileField(blank=True, upload_to=variableServer.models.Variable.get_upload_path),
        ),
    ]
