# Generated by Django 5.2.11 on 2026-03-05 10:48

import variableServer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variableServer', '0008_variable_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=variableServer.models.EncryptedField(blank=True, max_length=3000),
        ),
    ]
