# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/')),
                ('pixelsDiff', models.BinaryField(null=True)),
                ('refSnapshot', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.Snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('browser', models.CharField(max_length=20)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsession', to='snapshotServer.TestEnvironment')),
                ('testCases', models.ManyToManyField(blank=True, related_name='testsession', to='snapshotServer.TestCase')),
            ],
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='snapshotServer.Application')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='testSteps',
            field=models.ManyToManyField(blank=True, related_name='testCase', to='snapshotServer.TestStep'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCase', to='snapshotServer.Version'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.TestSession'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='snapshotServer.TestStep'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='testCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.TestCase'),
        ),
    ]
