# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonsServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/')),
                ('pixelsDiff', models.BinaryField(null=True)),
                ('tooManyDiffs', models.BooleanField(default=False)),
                ('refSnapshot', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.Snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='StepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('duration', models.FloatField(default=0.0)),
                ('stacktrace', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseInSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stacktrace', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('browser', models.CharField(max_length=20)),
                ('compareSnapshot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('commonsServer.application',),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('commonsServer.testcase',),
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('commonsServer.testenvironment',),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('commonsServer.version',),
        ),
        migrations.AddField(
            model_name='testsession',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsession', to='snapshotServer.TestEnvironment'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsession', to='snapshotServer.Version'),
        ),
        migrations.AddField(
            model_name='testcaseinsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.TestSession'),
        ),
        migrations.AddField(
            model_name='testcaseinsession',
            name='testCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCaseInSession', to='snapshotServer.TestCase'),
        ),
        migrations.AddField(
            model_name='testcaseinsession',
            name='testSteps',
            field=models.ManyToManyField(blank=True, related_name='testCase', to='snapshotServer.TestStep'),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stepresult', to='snapshotServer.TestStep'),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='testCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stepresult', to='snapshotServer.TestCaseInSession'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='stepResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='snapshotServer.StepResult'),
        ),
        migrations.AddField(
            model_name='excludezone',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.Snapshot'),
        ),
    ]
