# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relativePath', models.CharField(max_length=200)),
                ('browser', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.Application')),
            ],
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.TestEnvironment'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.TestStep'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='testCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.TestCase'),
        ),
    ]
