# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='relativePath',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='image',
            field=models.ImageField(default=None, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='snapshotServer.TestStep'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='testCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='snapshotServer.TestCase'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='snapshotServer.Application'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='snapshotServer.TestEnvironment'),
        ),
    ]
