# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.Snapshot')),
            ],
        ),
    ]
