# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0002_auto_20170726_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='session',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='step',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='testCase',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='stepResult',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='snapshotServer.StepResult'),
            preserve_default=False,
        ),
    ]
