# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0002_auto_20170222_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='testCase',
        ),
        migrations.AddField(
            model_name='teststep',
            name='testCase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teststep', to='snapshotServer.TestCase'),
        ),
    ]
