# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0002_excludezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testsession', to='snapshotServer.Version'),
            preserve_default=False,
        ),
    ]
