# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0003_testsession_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='tooManyDiffs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='sessionId',
            field=models.CharField(max_length=50),
        ),
    ]
