# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0003_auto_20170222_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='snapshotServer.Application')),
            ],
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='application',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='isReference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='difference',
            name='compared',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differenceComp', to='snapshotServer.Snapshot'),
        ),
        migrations.AddField(
            model_name='difference',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differenceRef', to='snapshotServer.Snapshot'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='version',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='snapshotServer.Version'),
            preserve_default=False,
        ),
    ]
