# Generated by Django 3.0.4 on 2020-04-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0004_auto_20200320_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='computed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='refSnapshot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='snapshotServer.Snapshot'),
        ),
    ]
