# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0004_testsession_comparesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepresult',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
