# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0004_auto_20170719_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='testenvironment',
            name='genericEnvironment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.TestEnvironment'),
        ),
    ]
