# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0005_difference_pixels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsession', to='snapshotServer.TestCase')),
            ],
        ),
        migrations.AddField(
            model_name='snapshot',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.TestSession'),
        ),
    ]
