# Generated by Django 3.2.2 on 2021-05-31 13:20

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    TestCaseInSession = apps.get_model("snapshotServer", "TestCaseInSession")
    TestStepsThroughTestCaseInSession = apps.get_model("snapshotServer", "TestStepsThroughTestCaseInSession")
    db_alias = schema_editor.connection.alias

    for test_case_in_session in TestCaseInSession.objects.using(db_alias).iterator():
        for test_step in test_case_in_session.testSteps.all():
            TestStepsThroughTestCaseInSession.objects.create(testcaseinsession=test_case_in_session, teststep=test_step, order=0)


def reverse_func(apps, schema_editor):
    TestStepsThroughTestCaseInSession = apps.get_model("snapshotServer", "TestStepsThroughTestCaseInSession")
    db_alias = schema_editor.connection.alias

    for throughModel in TestStepsThroughTestCaseInSession.objects.using(db_alias).iterator():
        testcaseinsession = throughModel.testcaseinsession
        teststep = throughModel.teststep
        testcaseinsession.testSteps.add(teststep)

class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0009_auto_20210225_0753'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='TestStepsThroughTestCaseInSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('testcaseinsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.testcaseinsession')),
                ('teststep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.teststep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='testcaseinsession',
            name='new_testSteps',
            field=models.ManyToManyField(blank=True, related_name='new_testCase', through='snapshotServer.TestStepsThroughTestCaseInSession', to='snapshotServer.TestStep'),
        ),
        
        migrations.RunPython(forwards_func, reverse_func),
        
        migrations.RemoveField(
            model_name='testcaseinsession',
            name='testSteps',
        ),
        
        migrations.RenameField(
            'testcaseinsession',              # model
            'new_testSteps',  # old field name
            'testSteps'   # new field name
        )
        
        ]
    
    
