# Generated by Django 3.2.2 on 2021-08-02 12:37

from django.db import migrations, models
import django.db.models.deletion
import snapshotServer.models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0010_auto_20210531_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseinsession',
            name='testSteps',
            field=models.ManyToManyField(blank=True, related_name='testCase', through='snapshotServer.TestStepsThroughTestCaseInSession', to='snapshotServer.TestStep'),
        ),
        migrations.CreateModel(
            name='StepReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=snapshotServer.models.upload_path)),
                ('stepResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_reference', to='snapshotServer.stepresult')),
            ],
        ),
    ]
