# Generated by Django 3.2.2 on 2023-02-01 15:20

from django.db import migrations, models
import snapshotServer.models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0011_auto_20210802_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepreference',
            name='image',
            field=models.ImageField(max_length=200, upload_to=snapshotServer.models.upload_path),
        ),
    ]
