# Generated by Django 3.2.18 on 2023-05-05 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0012_alter_stepreference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepreference',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.testenvironment'),
        ),
        migrations.AddField(
            model_name='stepreference',
            name='testCase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.testcase'),
        ),
        migrations.AddField(
            model_name='stepreference',
            name='testStep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.teststep'),
        ),
        migrations.AddField(
            model_name='stepreference',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshotServer.version'),
        ),
        migrations.AlterField(
            model_name='stepreference',
            name='stepResult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_reference', to='snapshotServer.stepresult'),
        ),
    ]
