# Generated by Django 3.2.18 on 2023-05-05 13:14

from django.db import migrations, models
import snapshotServer.models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0013_auto_20230505_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepreference',
            name='field_detection_data',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=snapshotServer.models.upload_path),
        ),
        migrations.AddField(
            model_name='stepreference',
            name='field_detection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepreference',
            name='field_detection_version',
            field=models.CharField(default='', max_length=10),
        ),
    ]
