# Generated by Django 3.2.18 on 2023-05-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0014_auto_20230505_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepreference',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
