# Generated by Django 3.2.18 on 2023-09-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0016_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='snapshotServer.testcaseinsession')),
            ],
        ),
    ]
