# Generated by Django 3.2.18 on 2023-10-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0017_executionlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinsession',
            name='status',
            field=models.CharField(default='SKIP', max_length=10),
        ),
    ]
