# Generated by Django 3.2.18 on 2023-10-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0019_testsession_comparesnapshotbehaviour'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinsession',
            name='gridNode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
