# Generated by Django 3.2.18 on 2023-10-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0020_testcaseinsession_gridnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='browser',
            field=models.CharField(max_length=100),
        ),
    ]
