# Generated by Django 3.2.18 on 2024-02-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0021_alter_testsession_browser'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinsession',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
