# Generated by Django 3.2.18 on 2024-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0025_testsession_startedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinsession',
            name='optimized',
            field=models.IntegerField(default=0),
        ),
    ]
