# Generated by Django 3.2.25 on 2024-12-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0026_testcaseinsession_optimized'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinsession',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
