# Generated by Django 3.2.25 on 2025-09-04 14:53

import commonsServer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0028_auto_20250502_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=commonsServer.models.TruncatingCharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='cause',
            field=commonsServer.models.TruncatingCharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='errorMessage',
            field=commonsServer.models.TruncatingCharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='exception',
            field=commonsServer.models.TruncatingCharField(default='', max_length=100, null=True),
        ),
    ]
