# Generated by Django 3.2.25 on 2026-02-04 13:09

import commonsServer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0029_auto_20250904_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='causeAnalysisErrors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='error',
            name='causeDetails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='error',
            name='causedBy',
            field=commonsServer.models.TruncatingCharField(max_length=100, null=True),
        ),
    ]
