# Generated by Django 3.2.25 on 2026-02-19 16:31

import commonsServer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0030_auto_20260204_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='element',
            field=commonsServer.models.TruncatingCharField(default='', max_length=150, null=True),
        ),
    ]
