# Generated by Django 5.2.11 on 2026-03-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0031_error_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='relatedErrors',
            field=models.ManyToManyField(to='snapshotServer.error'),
        ),
    ]
