# Generated by Django 5.1.15 on 2026-07-13 14:07

import commonsServer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0032_alter_error_relatederrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepresult',
            name='fullName',
            field=commonsServer.models.TruncatingCharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='meanHtmlLoadTimes',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='meanImageLoadTimes',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='meanJsLoadTimes',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='meanXhrLoadTimes',
            field=models.FloatField(default=-1.0),
        ),
    ]
