# Generated by Django 5.1.15 on 2026-06-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0032_alter_error_relatederrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcausefromuser',
            name='commentaire',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
