# Generated by Django 5.1.15 on 2026-08-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0033_stepresult_fullname_stepresult_meanhtmlloadtimes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepresult',
            name='networkErrors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
