# Generated by Django 5.1.15 on 2026-06-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0033_errorcausefromuser_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorcausefromuser',
            name='errorMessage',
            field=models.TextField(),
        ),
    ]
