# Generated by Django 5.1.15 on 2026-08-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0034_stepresult_networkerrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepresult',
            name='networkSlowness',
            field=models.TextField(blank=True, null=True),
        ),
    ]
