# Generated by Django 5.1.15 on 2026-09-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0034_alter_errorcausefromuser_errormessage'),
        ('snapshotServer', '0035_stepresult_networkslowness'),
    ]

    operations = [
    ]
