# Generated by Django 2.2.1 on 2019-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonsServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('locator', models.CharField(max_length=200)),
                ('tagName', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('coordX', models.IntegerField()),
                ('coordY', models.IntegerField()),
                ('lastUpdate', models.DateTimeField()),
                ('b64Image', models.BinaryField(max_length=20000)),
                ('attributes', models.CharField(max_length=1000)),
                ('totalSearch', models.IntegerField()),
                ('tagStability', models.IntegerField()),
                ('textStability', models.IntegerField()),
                ('rectangleStability', models.IntegerField()),
                ('b64ImageStability', models.IntegerField()),
                ('attributesStability', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': ('add', 'change', 'delete'),
                'indexes': [],
                'constraints': [],
            },
            bases=('commonsServer.application',),
        ),
    ]
