# Generated by Django 2.2.1 on 2019-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementInfoServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementinfo',
            name='attributes',
            field=models.CharField(default='{}', max_length=1000),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='attributesStability',
            field=models.CharField(default='{}', max_length=1000),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='b64Image',
            field=models.BinaryField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='b64ImageStability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='coordX',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='coordY',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='rectangleStability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='tagStability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='textStability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='totalSearch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementinfo',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
