# Generated by Django 2.2.1 on 2019-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonsServer', '0001_initial'),
        ('elementInfoServer', '0002_auto_20190628_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commonsServer.version',),
        ),
    ]
