# Generated by Django 2.2.1 on 2019-06-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elementInfoServer', '0003_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementinfo',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elementInfoServer.Application'),
        ),
        migrations.AddField(
            model_name='elementinfo',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elementInfoServer.Version'),
        ),
    ]
