# Generated by Django 2.2.1 on 2019-06-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementInfoServer', '0004_auto_20190628_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementinfo',
            name='b64Image',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
